<?xml version="1.0" encoding="utf-8"?><Database Name="Sach" Class="DBSachDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-D2NV4FV\MSSQLSERVER01;Initial Catalog=Sach;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SachConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="AuthorName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>